# Generated by Django 6.0.2 on 2026-02-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='feedback',
            new_name='improvement',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='interviewsession',
            name='end_time',
        ),
        migrations.AddField(
            model_name='answer',
            name='strengths',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='weaknesses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='tech_stack',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='overall_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='role',
            field=models.CharField(max_length=50),
        ),
    ]
